name: news_pro
description: A new Flutter project.
publish_to: "none"
version: 1.4.0+32

environment:
#  sdk: ">=2.15.1 <3.0.0"
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.1
  flutter_iconly: ^1.0.2
  auto_size_text: ^3.0.0
  animations: ^2.0.2
  easy_localization: ^3.0.2
  lottie: ^2.3.2
  flutter_riverpod: ^2.0.2
  flutter_html: ^3.0.0-beta.1
  flutter_html_audio: ^3.0.0-beta.1
  flutter_html_svg: ^3.0.0-beta.1
  flutter_html_table: ^3.0.0-beta.1
  flutter_html_video: ^3.0.0-alpha.4
  loading_animation_widget: ^1.1.0+1
  adaptive_theme: ^3.1.1
  fluttertoast: ^8.2.2
  shimmer: ^3.0.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  path_provider: ^2.0.9
  flutter_secure_storage: ^8.0.0
  validators: ^3.0.0
  intl: ^0.19.0
  share_plus: ^6.3.0
  firebase_core: ^2.4.0
  firebase_messaging: ^14.2.0
  url_launcher: ^6.0.20
  flutter_displaymode: ^0.6.0
  google_nav_bar: ^5.0.5
  internet_connection_checker: ^1.0.0+1
#  app_settings: ^4.1.1
  app_settings: ^5.1.1
  font_awesome_flutter: ^10.1.0
  sliver_tools: ^0.2.5
  flutter_web_browser: "^0.17.1"
  in_app_review: ^2.0.4
  uuid: ^3.0.6
  path: ^1.8.1
  loader_overlay: ^2.0.7
  flutter_staggered_animations: ^1.1.1
  collection: ^1.16.0
  connectivity_plus: ^4.0.1
  pod_player: ^0.1.0
  timeago: ^3.3.0
  html_unescape: ^2.0.0
  form_field_validator: ^1.1.0
  uni_links: ^0.5.1
  flutter_staggered_grid_view: ^0.6.2
  webview_flutter: ^4.0.5
  regexed_validator: ^2.0.0+1
  google_sign_in: ^6.0.2
  firebase_auth: ^4.3.0
  sign_in_with_apple: ^4.3.0
#  easy_ads_flutter: ^2.3.1
  dio: ^5.0.3
  dio_cache_interceptor: ^3.4.0
  google_mobile_ads: ^3.0.0
  cookie_consent: ^1.0.0
  wakelock: ^0.6.2
  flutter_inappwebview: ^6.0.0-beta.21
  linkable: ^3.0.1

  # Notes dependency
  get: ^4.6.5
  google_fonts: ^4.0.4

  # Translate dependency
  translator_plus: ^1.0.1

  # ChatRoom
  shared_preferences: ^2.2.1
  socket_io_client: ^2.0.3+1
  web_socket_channel: ^2.4.0

  # Questions
  websafe_svg: ^2.1.1 # to handle SVGs for Android, iOS, and Web
  flutter_svg: ^1.0.3 # to handle SVGs for Android, iOS, and Web

  # Terminology
  flutter_typeahead: ^4.8.0

  # SDK
  optimize_battery: ^0.0.4
  flutter_foreground_task: ^6.1.2

  # SDK-Notification
  android_intent_plus: ^4.0.3

  # App Update - Force
  flutter_dialogs: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.1.6
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.13.1
  custom_lint:
  riverpod_lint:
  build_runner: ^2.3.2


flutter_native_splash:
  color: "#ffffff"
  color_dark: "#1F2935"
  image: "assets/others/splash_logo_light.png"
  image_dark: "assets/others/splash_logo_dark.png"
  android: true
  ios: true
  web: false


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/others/logo.png"
  web:
    generate: false
  windows: 
    generate: false


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/illustration/
    - assets/others/
    - assets/animations/
    # Translations
    - assets/translations/
    - assets/translate/
    - assets/icons/
    - assets/questions_json/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 500
    - family: Nexa
      fonts:
        - asset: assets/fonts/Nexa-Heavy.ttf
          weight: 700
        - asset: assets/fonts/Nexa-ExtraLight.ttf
          weight: 300
    - family: Borela
      fonts:
        - asset: assets/fonts/BORELA.ttf
          weight: 700
dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre
  http: ^1.1.0
  visibility_detector: ^0.4.0+2
